# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- staging

pool:
  name: EdwinPool

jobs:
- job: Build_Deploy_Jobs
  timeoutInMinutes: 0

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      architecture: 'x64'
    displayName: 'Install Python3'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: '.env'
    
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Agent.TempDirectory)
      Contents: '**\.env'
      TargetFolder: $(System.DefaultWorkingDirectory)

  # Archive Django project and save it as a build artifact
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
      replaceExistingArchive: true
  - publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
    displayName: 'Upload package'
    artifact: drop

# Deploy to Azure App Service using zip deploy
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure Subscription 1383952(4b4cbe41-83a3-4832-9a89-e459c7fbfe0c)'
      appType: 'webAppLinux'
      AppName: 'webapp-firma-backend'
      ResourceGroupName: 'web-apps-rg'
      # packageForLinux: '$(System.DefaultWorkingDirectory)/drop/Application$(Build.BuildId).zip'
      package: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
      deploymentMethod: 'zipDeploy'
      RuntimeStack: 'PYTHON|3.10'
      StartupCommand: 'sh start.sh'
    displayName: 'Deploy to Azure Web App'
