version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
      - ./media/:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.environ/.dev
    depends_on:
      - redis
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_DB=sign_db
      - POSTGRES_USER=sign_dba
      - POSTGRES_PASSWORD=&yJ(jw5JM*dqjQ!8

  redis:
    image: "redis:7.0.7-alpine"
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: drf_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.environ/.dev
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: drf_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.environ/.dev
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.environ/.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
