version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - PGDATA=/var/lib/postgres/data/
      - POSTGRES_DB=sign_db
      - POSTGRES_USER=sign_dba
      - POSTGRES_PASSWORD=&yJ(jw5JM*dqjQ!8
    ports:
      - 5432:5432

  redis:
    image: "redis:7.0.7-alpine"
    ports:
      - 6379:6379

volumes:
  postgres_data:
