# Generated by Django 4.2 on 2024-05-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=20, null=True)),
                ("odoo_id", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee",
                "managed": True,
            },
        ),
    ]
