# Generated by Django 4.2 on 2023-05-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='document_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='odoo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
