# Generated by Django 4.1.3 on 2022-11-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='employeedata',
            table='employes_data',
        ),
    ]
