# Generated by Django 4.1.3 on 2022-12-21 23:54

import api.base.documents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_contract_table_alter_employeedata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(blank=True, max_length=255)),
                ('employess_data_name', models.CharField(blank=True, max_length=255)),
                ('contract_url', models.FileField(blank=True, upload_to=api.base.documents.models.upload_to)),
                ('employees_data_url', models.FileField(blank=True, upload_to=api.base.documents.models.upload_to)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='project',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.CreateModel(
            name='SignTask',
            fields=[
                ('input', models.IntegerField()),
                ('output', models.IntegerField(blank=True, null=True)),
                ('files', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='documents.files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=8)),
                ('message', models.CharField(blank=True, max_length=110)),
            ],
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='EmployeeData',
        ),
    ]
