# Generated by Django 4.1.3 on 2022-12-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_files_remove_employeedata_project_delete_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='contract_url',
            new_name='contract_template',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='employees_data_url',
            new_name='employees_data',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='employess_data_name',
            new_name='employees_data_name',
        ),
    ]
