# Generated by Django 4.1.3 on 2022-12-22 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_contract_url_files_contract_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signtask',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='signtask',
            old_name='modified_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='files',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='files',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='files',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
