# Generated by Django 4.2 on 2023-05-09 01:05

import api.base.documents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_document_id_employee_odoo_id_and_more'),
        ('documents', '0005_rename_created_at_signtask_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('path', models.FileField(blank=True, upload_to=api.base.documents.models.upload_to)),
                ('sign_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_document', to='employees.employee')),
            ],
            options={
                'db_table': 'contract_document',
                'managed': True,
            },
        ),
    ]
