# Generated by Django 4.2 on 2023-05-09 05:47

import api.base.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_contractdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('zip_file', models.FileField(blank=True, upload_to=api.base.documents.models.upload_to)),
                ('xlsx_file', models.FileField(blank=True, upload_to=api.base.documents.models.upload_to)),
                ('sign_number', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zip_file',
                'managed': True,
            },
        ),
    ]
