name: Deploy to GAE

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Connect to gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          export_default_credentials: true

      - name: Gather Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Run Migrations
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}